---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: install apache and php for CentOS servers
    dnf:
      name:
        - https
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
